---
# tasks file for bareos

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: bareos

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: bareos

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: bareos
